// ชื่อมหาวิทยาลัย, ระดับ (1-4), รหัสคณะ
const U=[
['จุฬาลงกรณ์มหาวิทยาลัย',1,'med den ph vet eng sci arch acc law eco pol arts edu nur com fa'],
['มหาวิทยาลัยมหิดล',1,'med den ph vet eng sci nur pub soc'],
['มหาวิทยาลัยธรรมศาสตร์',1,'med den ph eng sci arch acc law eco pol arts soc com nur pub'],
['มหาวิทยาลัยเกษตรศาสตร์',2,'eng sci ag vet bus eco soc hum edu arch'],
['มหาวิทยาลัยเชียงใหม่',2,'med den ph vet eng sci arch ag bus eco law pol hum soc edu nur pub com fa'],
['มหาวิทยาลัยขอนแก่น',2,'med den ph vet eng sci arch ag bus edu nur pub hum tech fa'],
['มหาวิทยาลัยสงขลานครินทร์',2,'med den ph vet eng sci nur law eco mgt hum edu com arch'],
['มหาวิทยาลัยศรีนครินทรวิโรฒ',2,'med den ph eng sci edu hum soc nur com'],
['มหาวิทยาลัยศิลปากร',2,'arch eng sci ph fa arts edu'],
['มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี',2,'eng sci arch'],
['สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง',2,'eng sci arch tech ag'],
['มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ',3,'eng sci tech'],
['มหาวิทยาลัยบูรพา',3,'med eng sci edu hum soc bus nur pub com'],
['มหาวิทยาลัยนเรศวร',3,'med den ph eng sci arch ag law nur pub edu hum soc bus'],
['มหาวิทยาลัยมหาสารคาม',3,'med ph eng sci edu hum soc nur pub mgt tech'],
['มหาวิทยาลัยอุบลราชธานี',3,'eng sci ag ph nur law pol bus'],
['มหาวิทยาลัยแม่ฟ้าหลวง',3,'med sci mgt arts nur'],
['มหาวิทยาลัยวลัยลักษณ์',3,'med eng sci ph nur law mgt arts'],
['มหาวิทยาลัยเทคโนโลยีสุรนารี',3,'med eng sci ag nur soc'],
['มหาวิทยาลัยพะเยา',3,'med ph eng sci nur law mgt'],
['มหาวิทยาลัยทักษิณ',3,'edu sci hum soc nur eng'],
['มหาวิทยาลัยแม่โจ้',3,'ag sci eng bus tech'],
['มหาวิทยาลัยรามคำแหง',4,'law eco bus arts hum edu sci eng com'],
['มหาวิทยาลัยหอการค้าไทย',4,'acc bus eco eng com law'],
['มหาวิทยาลัยรังสิต',4,'med den ph eng sci arch bus law com nur'],
['มหาวิทยาลัยกรุงเทพ',4,'bus eng com law arch fa'],
['มหาวิทยาลัยอัสสัมชัญ',4,'bus eng com arts law'],
['มหาวิทยาลัยศรีปทุม',4,'bus eng law com arch'],
['มหาวิทยาลัยราชภัฏสวนสุนันทา',4,'edu hum mgt sci tech'],
['มหาวิทยาลัยราชภัฏสวนดุสิต',4,'edu mgt nur'],
['มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี',4,'eng tech sci ag']
];
